-- ═══════════════════════════════════════════════════════════════
-- CUBO POLAR ERP — Migration 004: Control Financiero COMPLETO
-- Crea todo lo necesario para CxC, pagos y folios
-- Ejecutar en Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────
-- 1. SECUENCIAS para folios (IF NOT EXISTS para evitar errores)
-- ───────────────────────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'folio_ov_seq') THEN
    CREATE SEQUENCE folio_ov_seq START WITH 1;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'folio_op_seq') THEN
    CREATE SEQUENCE folio_op_seq START WITH 1;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'folio_r_seq') THEN
    CREATE SEQUENCE folio_r_seq START WITH 1;
  END IF;
END $$;

-- ───────────────────────────────────────────────────────────────
-- 2. FUNCIÓN nextval (wrapper para secuencias desde el frontend)
-- ───────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION nextval(seq_name TEXT)
RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE result BIGINT;
BEGIN
  EXECUTE format('SELECT nextval(%L)', seq_name) INTO result;
  RETURN result;
END;
$$;

-- ───────────────────────────────────────────────────────────────
-- 3. CREAR TABLA cuentas_por_cobrar
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cuentas_por_cobrar (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id      BIGINT NOT NULL REFERENCES clientes(id),
  orden_id        BIGINT REFERENCES ordenes(id),
  fecha_venta     DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_vencimiento DATE,
  monto_original  NUMERIC NOT NULL DEFAULT 0,
  monto_pagado    NUMERIC NOT NULL DEFAULT 0,
  saldo_pendiente NUMERIC NOT NULL DEFAULT 0,
  estatus         TEXT NOT NULL DEFAULT 'Pendiente',  -- Pendiente, Parcial, Pagada, Vencida
  concepto        TEXT DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RLS para cuentas_por_cobrar
ALTER TABLE cuentas_por_cobrar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cxc_read_all" ON cuentas_por_cobrar;
DROP POLICY IF EXISTS "cxc_write" ON cuentas_por_cobrar;
CREATE POLICY "cxc_read_all" ON cuentas_por_cobrar FOR SELECT TO authenticated USING (true);
CREATE POLICY "cxc_write" ON cuentas_por_cobrar FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ───────────────────────────────────────────────────────────────
-- 4. AGREGAR COLUMNAS A pagos
-- ───────────────────────────────────────────────────────────────
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS orden_id BIGINT REFERENCES ordenes(id);
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS metodo_pago TEXT DEFAULT 'Efectivo';
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS fecha DATE DEFAULT CURRENT_DATE;
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS cxc_id BIGINT REFERENCES cuentas_por_cobrar(id);

-- ───────────────────────────────────────────────────────────────
-- 5. ÍNDICES para consultas rápidas
-- ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_pagos_fecha ON pagos(fecha);
CREATE INDEX IF NOT EXISTS idx_pagos_orden ON pagos(orden_id);
CREATE INDEX IF NOT EXISTS idx_pagos_cxc ON pagos(cxc_id);
CREATE INDEX IF NOT EXISTS idx_cxc_cliente ON cuentas_por_cobrar(cliente_id);
CREATE INDEX IF NOT EXISTS idx_cxc_estatus ON cuentas_por_cobrar(estatus);
CREATE INDEX IF NOT EXISTS idx_cxc_vencimiento ON cuentas_por_cobrar(fecha_vencimiento);

-- ───────────────────────────────────────────────────────────────
-- 6. RLS para pagos
-- ───────────────────────────────────────────────────────────────
ALTER TABLE pagos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pagos_read_all" ON pagos;
DROP POLICY IF EXISTS "pagos_write" ON pagos;
CREATE POLICY "pagos_read_all" ON pagos FOR SELECT TO authenticated USING (true);
CREATE POLICY "pagos_write" ON pagos FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ───────────────────────────────────────────────────────────────
-- 7. FUNCIÓN para incrementar/decrementar saldo de cliente
-- ───────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION increment_saldo(p_cli BIGINT, p_delta NUMERIC)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  UPDATE clientes SET saldo = saldo + p_delta WHERE id = p_cli;
END;
$$;

-- ───────────────────────────────────────────────────────────────
-- 8. TRIGGERS updated_at (si no existen)
-- ───────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_cxc_updated ON cuentas_por_cobrar;
CREATE TRIGGER trg_cxc_updated BEFORE UPDATE ON cuentas_por_cobrar 
FOR EACH ROW EXECUTE FUNCTION update_updated_at();
