-- ═══════════════════════════════════════════════════════════════
-- CUBO POLAR ERP — Migration 005: Rutas Mejoradas
-- Plantillas de ruta con clientes preestablecidos
-- Carga y extra autorizado por producto
-- ═══════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────
-- 1. TABLA: Plantillas de Ruta (rutas preestablecidas con clientes)
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ruta_plantillas (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          TEXT NOT NULL,                    -- Ej: "Ruta Norte", "Ruta Centro"
  chofer_id       BIGINT REFERENCES usuarios(id),  -- Chofer default asignado
  dias_semana     TEXT[] DEFAULT '{}',              -- Ej: ['Lunes','Miércoles','Viernes']
  activa          BOOLEAN DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ───────────────────────────────────────────────────────────────
-- 2. TABLA: Clientes asignados a cada plantilla de ruta
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ruta_plantilla_clientes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plantilla_id    BIGINT NOT NULL REFERENCES ruta_plantillas(id) ON DELETE CASCADE,
  cliente_id      BIGINT NOT NULL REFERENCES clientes(id),
  orden           INTEGER DEFAULT 0,                -- Orden de visita
  carga_sugerida  JSONB DEFAULT '{}',               -- Carga típica: {"HC-25K": 10, "HC-5K": 5}
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(plantilla_id, cliente_id)
);

-- ───────────────────────────────────────────────────────────────
-- 3. AGREGAR COLUMNAS A rutas (para carga por producto)
-- ───────────────────────────────────────────────────────────────
-- La columna carga ya existe como JSONB, agregaremos más columnas
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS plantilla_id BIGINT REFERENCES ruta_plantillas(id);
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS carga_autorizada JSONB DEFAULT '{}';   -- {"HC-25K": 50, "HC-5K": 30, ...}
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS extra_autorizado JSONB DEFAULT '{}';   -- Extra por producto
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS carga_real JSONB DEFAULT '{}';          -- Lo que realmente cargó
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS devolucion JSONB DEFAULT '{}';          -- Lo devuelto por producto
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS autorizado_por BIGINT REFERENCES usuarios(id);
ALTER TABLE rutas ADD COLUMN IF NOT EXISTS autorizado_at TIMESTAMPTZ;

-- ───────────────────────────────────────────────────────────────
-- 4. ÍNDICES
-- ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_ruta_plantillas_chofer ON ruta_plantillas(chofer_id);
CREATE INDEX IF NOT EXISTS idx_ruta_plantilla_clientes_plantilla ON ruta_plantilla_clientes(plantilla_id);
CREATE INDEX IF NOT EXISTS idx_rutas_plantilla ON rutas(plantilla_id);
CREATE INDEX IF NOT EXISTS idx_rutas_fecha ON rutas(fecha);

-- ───────────────────────────────────────────────────────────────
-- 5. RLS
-- ───────────────────────────────────────────────────────────────
ALTER TABLE ruta_plantillas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "plantillas_read" ON ruta_plantillas;
DROP POLICY IF EXISTS "plantillas_write" ON ruta_plantillas;
CREATE POLICY "plantillas_read" ON ruta_plantillas FOR SELECT TO authenticated USING (true);
CREATE POLICY "plantillas_write" ON ruta_plantillas FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE ruta_plantilla_clientes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "plantilla_clientes_read" ON ruta_plantilla_clientes;
DROP POLICY IF EXISTS "plantilla_clientes_write" ON ruta_plantilla_clientes;
CREATE POLICY "plantilla_clientes_read" ON ruta_plantilla_clientes FOR SELECT TO authenticated USING (true);
CREATE POLICY "plantilla_clientes_write" ON ruta_plantilla_clientes FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ───────────────────────────────────────────────────────────────
-- 6. TRIGGERS updated_at
-- ───────────────────────────────────────────────────────────────
DROP TRIGGER IF EXISTS trg_ruta_plantillas_updated ON ruta_plantillas;
CREATE TRIGGER trg_ruta_plantillas_updated BEFORE UPDATE ON ruta_plantillas 
FOR EACH ROW EXECUTE FUNCTION update_updated_at();
