-- ═══════════════════════════════════════════════════════════════
-- CUBO POLAR ERP — Migration 006: Catálogo de Costos y Gastos
-- Costos fijos recurrentes, costos variables, costo de producción
-- ═══════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────
-- 1. TABLA: Catálogo de Costos Fijos (gastos recurrentes)
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS costos_fijos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre          TEXT NOT NULL,                    -- Ej: "Renta bodega", "Luz CFE"
  categoria       TEXT NOT NULL DEFAULT 'Operación', -- Nómina, Renta, Servicios, Mantenimiento, Otro
  monto           NUMERIC NOT NULL DEFAULT 0,       -- Monto mensual fijo
  frecuencia      TEXT NOT NULL DEFAULT 'Mensual',  -- Mensual, Quincenal, Semanal
  dia_cargo       INTEGER DEFAULT 1,                -- Día del mes/semana que se carga
  activo          BOOLEAN DEFAULT TRUE,
  proveedor       TEXT DEFAULT '',                  -- Nombre del proveedor
  cuenta_pago     TEXT DEFAULT '',                  -- Cuenta bancaria / método
  notas           TEXT DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ───────────────────────────────────────────────────────────────
-- 2. TABLA: Historial de costos aplicados (egresos generados)
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS costos_historial (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  costo_fijo_id   BIGINT REFERENCES costos_fijos(id),
  tipo            TEXT NOT NULL,                    -- 'Fijo', 'Variable', 'Nómina', 'Producción'
  categoria       TEXT NOT NULL,
  concepto        TEXT NOT NULL,
  monto           NUMERIC NOT NULL DEFAULT 0,
  periodo         TEXT,                             -- Ej: "2026-03", "S10-2026"
  fecha           DATE NOT NULL DEFAULT CURRENT_DATE,
  referencia      TEXT DEFAULT '',                  -- Factura, recibo, etc.
  movimiento_id   BIGINT REFERENCES movimientos_contables(id), -- Link al egreso
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ───────────────────────────────────────────────────────────────
-- 3. AGREGAR COLUMNAS a productos (costo unitario para empaques)
-- ───────────────────────────────────────────────────────────────
ALTER TABLE productos ADD COLUMN IF NOT EXISTS costo_unitario NUMERIC DEFAULT 0;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS proveedor TEXT DEFAULT '';
ALTER TABLE productos ADD COLUMN IF NOT EXISTS ultimo_costo_fecha DATE;
ALTER TABLE productos ADD COLUMN IF NOT EXISTS empaque_sku TEXT DEFAULT NULL;  -- Vincula producto terminado con su empaque

-- ───────────────────────────────────────────────────────────────
-- 4. AGREGAR COLUMNAS a produccion (costo calculado)
-- ───────────────────────────────────────────────────────────────
ALTER TABLE produccion ADD COLUMN IF NOT EXISTS costo_empaque NUMERIC DEFAULT 0;
ALTER TABLE produccion ADD COLUMN IF NOT EXISTS costo_total NUMERIC DEFAULT 0;

-- ───────────────────────────────────────────────────────────────
-- 5. AGREGAR COLUMNAS a nomina_periodos (para tracking de pago)
-- ───────────────────────────────────────────────────────────────
ALTER TABLE nomina_periodos ADD COLUMN IF NOT EXISTS total_neto NUMERIC DEFAULT 0;
ALTER TABLE nomina_periodos ADD COLUMN IF NOT EXISTS estatus TEXT DEFAULT 'Pendiente';
ALTER TABLE nomina_periodos ADD COLUMN IF NOT EXISTS pagado_at TIMESTAMPTZ;
ALTER TABLE nomina_periodos ADD COLUMN IF NOT EXISTS movimiento_id BIGINT REFERENCES movimientos_contables(id);

-- ───────────────────────────────────────────────────────────────
-- 5B. TABLA: Cuentas por Pagar (deudas con proveedores)
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cuentas_por_pagar (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor         TEXT NOT NULL,                    -- Nombre del proveedor
  concepto          TEXT NOT NULL,                    -- Descripción de la deuda
  monto_original    NUMERIC NOT NULL DEFAULT 0,       -- Monto total de la deuda
  monto_pagado      NUMERIC NOT NULL DEFAULT 0,       -- Cuánto se ha abonado
  saldo_pendiente   NUMERIC NOT NULL DEFAULT 0,       -- Lo que falta por pagar
  fecha_emision     DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_vencimiento DATE,                             -- Cuándo vence
  estatus           TEXT DEFAULT 'Pendiente',         -- Pendiente, Parcial, Pagada
  categoria         TEXT DEFAULT 'Proveedores',       -- Proveedores, Servicios, Otros
  referencia        TEXT DEFAULT '',                  -- # Factura, contrato, etc.
  notas             TEXT DEFAULT '',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabla de pagos a proveedores (abonos a CxP)
CREATE TABLE IF NOT EXISTS pagos_proveedores (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cxp_id          BIGINT REFERENCES cuentas_por_pagar(id) ON DELETE CASCADE,
  monto           NUMERIC NOT NULL DEFAULT 0,
  fecha           DATE NOT NULL DEFAULT CURRENT_DATE,
  metodo_pago     TEXT DEFAULT 'Transferencia',
  referencia      TEXT DEFAULT '',
  movimiento_id   BIGINT REFERENCES movimientos_contables(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ───────────────────────────────────────────────────────────────
-- 6. ÍNDICES
-- ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_costos_fijos_categoria ON costos_fijos(categoria);
CREATE INDEX IF NOT EXISTS idx_costos_fijos_activo ON costos_fijos(activo);
CREATE INDEX IF NOT EXISTS idx_costos_historial_fecha ON costos_historial(fecha);
CREATE INDEX IF NOT EXISTS idx_costos_historial_tipo ON costos_historial(tipo);
CREATE INDEX IF NOT EXISTS idx_costos_historial_periodo ON costos_historial(periodo);

-- ───────────────────────────────────────────────────────────────
-- 7. RLS
-- ───────────────────────────────────────────────────────────────
ALTER TABLE costos_fijos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "costos_fijos_read" ON costos_fijos;
DROP POLICY IF EXISTS "costos_fijos_write" ON costos_fijos;
CREATE POLICY "costos_fijos_read" ON costos_fijos FOR SELECT TO authenticated USING (true);
CREATE POLICY "costos_fijos_write" ON costos_fijos FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE costos_historial ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "costos_historial_read" ON costos_historial;
DROP POLICY IF EXISTS "costos_historial_write" ON costos_historial;
CREATE POLICY "costos_historial_read" ON costos_historial FOR SELECT TO authenticated USING (true);
CREATE POLICY "costos_historial_write" ON costos_historial FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ───────────────────────────────────────────────────────────────
-- 8. TRIGGERS updated_at
-- ───────────────────────────────────────────────────────────────
DROP TRIGGER IF EXISTS trg_costos_fijos_updated ON costos_fijos;
CREATE TRIGGER trg_costos_fijos_updated BEFORE UPDATE ON costos_fijos 
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_cxp_updated ON cuentas_por_pagar;
CREATE TRIGGER trg_cxp_updated BEFORE UPDATE ON cuentas_por_pagar 
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ───────────────────────────────────────────────────────────────
-- 8B. RLS para Cuentas por Pagar
-- ───────────────────────────────────────────────────────────────
ALTER TABLE cuentas_por_pagar ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cxp_read" ON cuentas_por_pagar;
DROP POLICY IF EXISTS "cxp_write" ON cuentas_por_pagar;
CREATE POLICY "cxp_read" ON cuentas_por_pagar FOR SELECT TO authenticated USING (true);
CREATE POLICY "cxp_write" ON cuentas_por_pagar FOR ALL TO authenticated USING (true) WITH CHECK (true);

ALTER TABLE pagos_proveedores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pagos_prov_read" ON pagos_proveedores;
DROP POLICY IF EXISTS "pagos_prov_write" ON pagos_proveedores;
CREATE POLICY "pagos_prov_read" ON pagos_proveedores FOR SELECT TO authenticated USING (true);
CREATE POLICY "pagos_prov_write" ON pagos_proveedores FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ───────────────────────────────────────────────────────────────
-- 8C. ÍNDICES para CxP
-- ───────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_cxp_proveedor ON cuentas_por_pagar(proveedor);
CREATE INDEX IF NOT EXISTS idx_cxp_estatus ON cuentas_por_pagar(estatus);
CREATE INDEX IF NOT EXISTS idx_cxp_vencimiento ON cuentas_por_pagar(fecha_vencimiento);
CREATE INDEX IF NOT EXISTS idx_pagos_prov_cxp ON pagos_proveedores(cxp_id);

-- ───────────────────────────────────────────────────────────────
-- 9. DATOS INICIALES - Categorías comunes de costos
-- ───────────────────────────────────────────────────────────────
-- (Opcional: descomentar para insertar ejemplos)
-- INSERT INTO costos_fijos (nombre, categoria, monto, frecuencia) VALUES
--   ('Renta bodega', 'Renta', 15000, 'Mensual'),
--   ('Luz CFE', 'Servicios', 8000, 'Mensual'),
--   ('Agua SAPAL', 'Servicios', 1500, 'Mensual'),
--   ('Internet Telmex', 'Servicios', 800, 'Mensual'),
--   ('Mantenimiento máquinas', 'Mantenimiento', 5000, 'Mensual'),
--   ('Gasolina rutas', 'Combustible', 12000, 'Semanal');
