[[redirects]]
  from = "/pagar/:id"
  to = "/.netlify/functions/billing-pay?o=:id"
  status = 200
  force = true

[[redirects]]
  from = "/pago-resultado"
  to = "/.netlify/functions/billing-result"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
